//UISTATE
export const RUNNING = 'RUNNING';


//USERINFO
export const SET_CURRENT_USER_ID = 'SET_CURRENT_USER_ID';
export const SET_CURRENT_USER_NAME = 'SET_CURRENT_USER_NAME';
export const ADD_LOCATION_TO_USER = 'ADD_LOCATION_TO_USER';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const SET_CURRENT_USER_ROLE = 'SET_CURRENT_USER_ROLE';
export const SET_USER_ROLE = 'SET_USER_ROLE';

//SESSIONSTATE
export const SET_SESSION_NAME = 'SET_SESSION_NAME';
export const SET_SESSION_CREATED = 'SET_SESSION_CREATED';
